name: Publish release

on:
  workflow_dispatch:

jobs:
  get_release_version:
    name: Get Release Version
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: execute
        run: |
          export VERSION="$((grep -w 'version' | cut -d= -f2) < gradle.properties | cut -d- -f1)"
          echo "::set-output name=version::${VERSION}"
    outputs:
      version: ${{steps.execute.outputs.version}}
  create_release:
    needs: get_release_version
    name: Create Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        with:
          tag_name: ${{ needs.get_release_version.outputs.version }}
          release_name: ${{ needs.get_release_version.outputs.version }}
          draft: false
          prerelease: false
  release_assets:
    name: Release assets
    needs: [ get_release_version, create_release ]
    runs-on: ${{ matrix.os }}
    if: github.repository_owner == 'ballerina-platform'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest-x64, macOS-latest-arm64 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JRE on Linux
        if: matrix.os == 'ubuntu-latest'
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: ./gradlew build
      - name: Build JRE on Windows
        if: matrix.os == 'windows-latest'
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: ./gradlew.bat build
      - name: Build JRE on macOS
        if: contains(matrix.os, 'macOS-latest')
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: ./gradlew build
      - name: Upload linux artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ballerina-jre-linux-64-${{ needs.get_release_version.outputs.version }}.zip
          asset_path: build/distributions/ballerina-jre-linux-64-${{ needs.get_release_version.outputs.version }}-SNAPSHOT.zip
          asset_content_type: application/octet-stream
      - name: Upload windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ballerina-jre-windows-64-${{ needs.get_release_version.outputs.version }}.zip
          asset_path: build/distributions/ballerina-jre-windows-64-${{ needs.get_release_version.outputs.version }}-SNAPSHOT.zip
          asset_content_type: application/octet-stream
      - name: Upload macOS artifacts
        if: matrix.os == 'macOS-latest-x64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ballerina-jre-macos-64-${{ needs.get_release_version.outputs.version }}.zip
          asset_path: build/distributions/ballerina-jre-macos-64-${{ needs.get_release_version.outputs.version }}-SNAPSHOT.zip
          asset_content_type: application/octet-stream
      - name: Upload macOS-ARM artifacts
        if: matrix.os == 'macOS-latest-arm64'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ballerina-jre-macos-arm-64-${{ needs.get_release_version.outputs.version }}.zip
          asset_path: build/distributions/ballerina-jre-macos-arm-64-${{ needs.get_release_version.outputs.version }}-SNAPSHOT.zip
          asset_content_type: application/octet-stream
